version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - ENVIRONMENT=staging
      - LOG_LEVEL=info
      - DEBUG=false
      - CORS_ORIGINS=${CORS_ORIGINS:-https://staging.authsystem.com}
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_STAGING}
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    ports: []  # Don't expose externally

  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD_STAGING}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD_STAGING}
    ports: []  # Don't expose externally

volumes:
  postgres_staging_data:

