name: Frontend Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'auth-frontend/**'
      - '.github/workflows/frontend-tests.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'auth-frontend/**'
      - '.github/workflows/frontend-tests.yml'

jobs:
  frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: auth-frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: auth-frontend
        run: npm ci
      
      - name: Run linter
        working-directory: auth-frontend
        run: npm run lint
      
      - name: Run type check
        working-directory: auth-frontend
        run: npx tsc --noEmit
        continue-on-error: true
      
      - name: Run tests with coverage
        working-directory: auth-frontend
        run: npm run test:coverage
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: auth-frontend/coverage/coverage-final.json
          flags: frontend
          name: frontend-coverage
        continue-on-error: true
      
      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: frontend-coverage-report
          path: auth-frontend/coverage/
          retention-days: 30
      
      - name: Comment PR with coverage
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: auth-frontend/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      
      - name: Build project
        working-directory: auth-frontend
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: auth-frontend/dist/
          retention-days: 7

  frontend-e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: auth-frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: auth-frontend
        run: npm ci
      
      - name: Install Playwright browsers
        working-directory: auth-frontend
        run: npx playwright install --with-deps
      
      - name: Run E2E tests
        working-directory: auth-frontend
        run: npm run test:e2e
      
      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: auth-frontend/playwright-report/
          retention-days: 30

